microcoap/Makefile, microcoap/README.md, microcoap/endpoints.c, microcoap/main.c
Add a small microcoap example server along with instructions on how to test it using [marz](https://github.com/sgso/marz) and the Copper Firefox Plugin. Depends on https://github.com/RIOT-OS/RIOT/pull/2383.
=> add microcoap example application

ng_sniffer/Makefile, ng_sniffer/README.md, ng_sniffer/main.c
This is the adaption of the existing sniffer application to work with the new network stack.
This PR works so far only with `at86rf2xx` drivers, e.g. with the `iot-lab_M3` or the `samr21-xpro` boards.
=> ng_sniffer: added ng version of sniffer application

sixlowapp/main.c
The constants names changed in the past:
https://github.com/RIOT-OS/RIOT/commit/426170b06439badf41818a58b37117aac26806a9
=> sixlowapp: rename thread related constants

ng_sniffer/Makefile
This application was not adapted to https://github.com/RIOT-OS/RIOT/pull/3162 and https://github.com/RIOT-OS/RIOT/pull/3188
=> ng_sniffer: added ng_netif_default

ng_sniffer/Makefile, ng_sniffer/main.c
Related and dependent on https://github.com/RIOT-OS/RIOT/pull/3555
=> ng_sniffer: use uart0 only for none newlib boards

openwsn/Makefile, openwsn/main.c
`vtimer` does not exist anymore.
For what was the `vtimer` used before? Maybe we can omit the timer completely instead of just replacing it with `xtimer`?
=> openwsn: remove vtimer, use xtimer

sniffer/main.c
The sniffer wasn't compiling after https://github.com/RIOT-OS/RIOT/pull/5526 was merged
=> sniffer: Update to follow gnrc_netreg_entry_t API change

sniffer/main.c
Updated to fix compilation errors after some xtimer API changes. Changed printf to avoid relying on support in printf for 64 bit numbers, since it is a trivial workaround when printing in hex and some newlib builds may not have this support for code size reasons.
=> sniffer: update to match xtimer API changes

sniffer/main.c
Usually we have a message queue for threads handling GNRC netapi calls. Maybe the absence of one in this application contributes to the packet loss reported at various places.
Usually this reported as an error, but since `DEVELHELP` is not enabled for this application (and it shouldn't), this did not show up.
Fixes #32 (see https://github.com/RIOT-OS/applications/pull/34#issuecomment-398179602)
=> sniffer: add message queue for dumper thread

sniffer/main.c
Since the device is in raw mode, we don't have any network layer
modules included and we subscribe to `GNRC_NETTYPE_UNDEF` it is safe
to assume that `pkt->next` in `dump_pkt()` is the `gnrc_netif` header.
This only contains GNRC-internal information and should thus be removed
from the dump (though Wireshark seems to be okay with the extra bytes,
a reader of the raw data might be confused).
Since this header however contains the LQI, which the sniffer claims to
output but always returns 0, the LQI value in the `gnrc_netif` header
is read and set before the deletion of that header.
=> sniffer: remove gnrc_netif header; read LQI

sniffer/tools/sniffer.py
This is mainly a preparation step to make some arguments (namely
baudrate and the "serial/socket" argument) optional, to make it more
usable like the old `rftest2pcap` script for the econotag.
(it also makes the script code more readable)
=> sniffer: use argparse to parse script arguments

sniffer/tools/sniffer.py
=>  sniffer: make baudrate optional

sniffer/tools/sniffer.py
The sniffer RIOT application doesn't generate non-ASCII characters so it
is safe for the python PCAP-generating script to assume that those
characters are garbage output (e.g. in initialization) and can be
ignored.
=> sniffer: script: ignore non-ASCII characters on input

sniffer/tools/sniffer.py
This fixes a minor typo in the `sniffer.py` script where the default baud rate is set to `112500` instead of `115200`.
=> sniffer: fix default baudrate in script

sniffer/Makefile, sniffer/main.c, sniffer/tools/sniffer.py
I know this is  a little more extreme change, but I was able to reduce stack usage by 2/3 on `samr21-xpro`. Additionally, I removed the leading `0x` for the hexadecimal numbers. The parsing script knows which numbers are hex (all of them) and they just waste time both on the node and in the parsing script.
(~~Needs to be adapted if #33 is merged before~~ done)
=>  sniffer: use fmt instead of printf

spectrum-scanner/Makefile, spectrum-scanner/main.c
The application does not compile with current RIOT master, this PR fixes that and
adapt the gnrc_netif calls accordingly.
Additionally this PR changes the default board in the Makefile from `frdm-kw41z` to `samr21-xpro` as this seems to be the only board with a radio driver in RIOT that supports the required NETOPT.
To test: try to compile spectrum-scanner in master with current RIOT which will fail. While this PR does work.
=> spektrum scanner: adapt to new gnrc_netif calls

spectrum-scanner/tools/plot_rssi.py
Adapt python script to comply with python coding conventions, i.e.
fixing error reported by flake8.
=> spektrum-scanner: fix plot_rssi.py script

coap-chat/Makefile, coap-chat/README.md, coap-chat/coap.c, coap-chat/main.c
This application allows to send (small) messages via CoAP to any
destination address. To chat locally you may use `ff02::1` to reach
neighbouring nodes, or chat directly using unicast addresses. The
application provides a distinct shell command `chat` but also brings
standard shell commands like `ifconfig` to show a nodes IP addresses.
=> coap-chat: a simple chat application using gCoAP

sniffer/main.c
Avoids a hard fault when using the latest RIOT master where raw mode does not provide a netif header.
The sniffer application works without this PR on samr21-xpro, but only because of luck.
https://github.com/RIOT-OS/applications/blob/39a974efcae7161b0b319972a55b3d60c171076a/sniffer/main.c#L61 `pkt->next` is NULL and the pktbuf_remove call causes an indirect write: `pkt->next->next = NULL;`
On frdm-kw41z (with RIOT-OS/RIOT#7107) the null pointer write causes a hard fault
for reference, here is the called function where the write happens: https://github.com/RIOT-OS/RIOT/blob/f139dfdad2c81f239e27e2be86a7857e740dc201/sys/net/gnrc/pktbuf/gnrc_pktbuf.c#L54-L62
=> sniffer: Check for missing netif header in dump_pkt

.gitmodules, coap-chat/Makefile, sniffer/Makefile, spectrum-scanner/Makefile
This adds RIOT as a submodule fixed on the latest official release, i.e., ~~2018.07~~ 2018.10. It also adapts the Makefiles of the ~~2~~ 3 existing apps to use the submodule as RIOTBASE.
The idea would be that the submodule is bumped to the next version (RIOT release) as part of the release process and with that make sure all apps compile and run with the new release. This would
help to allow problems like #47 where the app is broken because of changes to RIOT master.
=> add RIOT as submodule

.travis.yml
This PR does a couple of things to enable an initial CI check on applications:
~~1. it add the current/latest RIOT release as a submodule to this repository~~
~~2. RIOTBASE of all application Makefiles is adapted to point to the submodule~~
3. an initial travis.yml is added, that runs some static tests reusing scripts and config from the RIOT submodule
~~4. adds a patch for the `plot_rssi.py` of the spectrum-scanner to fix flake8 errors~~
~~The idea for the future would be that applications always work against the latest RIOT release and as part of the release process the submodule hash is updated every 3 month (or so). That way applications should work from release to release.~~
Note: I think someone with more GitHub rights than me has to enable Travis for this repo (@miri64?).
=> CI: add travis config

README.md
Provides a README with some instructions (and the current build status of the repo).
=> Provide README

spectrum-scanner/tools/plot_rssi.py
This is a rewrite of the plotting script used by the spectrum scanner.
Improvements:
- No longer steals window focus at each data update
- Uses matplotlib's animation API for live updates, instead of manually re-plotting on a timer loop
- Newest values are always at the right hand side of the plot area
- Added workaround for issue mentioned in https://github.com/RIOT-OS/RIOT/pull/1437/commits/73f6a0c51815144a128f3a368fafae73b1b69215 (problem was observed with FRDM-KW41Z)
=> spectrum-scanner: Improved plotting script

coap-chat/coap.c
Fixes straightforward compilation issue due to upstream change to gcoap in 2019.10 release.
Compile for native, use `tapsetup` to create a couple of tap interfaces, then try a short chat.
Depends on #67
=> coap-chat: 2019.10 update

README.md, coap-chat/coap.c
This PR bump the version to the latest release and fixes the README submodule init code.
Applications test:
- sniffer
```
/workspace/riot-applications/sniffer/tools/sniffer.py -b 500000 /dev/riot/tty-iotlab-m3 26 | wireshark -k -i -
ifconfig 3 set chan 26
ifconfig 3 raw
ifconfig 3 promisc
```
- spectrum scanner:
```
2020-02-05 10:13:36,259 # [0, 502287, 42] 11: -87.8340, 12: -84.1664, 13: -86.3273, 14: -87.2096, 15: -90.1427, 16: -90.0974, 17: -90.4618, 18: -90.5094, 19: -88.6544, 20: -88.8523, 21: -89.8233, 22: -87.4000, 23: -90.7352, 24: -90.9999, 25: -90.9999, 26: -90.9999, 
2020-02-05 10:13:36,262 # [0, 1013032, 42] 11: -89.3162, 12: -87.2324, 13: -85.8784, 14: -88.8112, 15: -90.2932, 16: -90.3245, 17: -90.7360, 18: -88.1828, 19: -87.0150, 20: -87.8800, 21: -90.8786, 22: -89.7652, 23: …
```
=> RIOT: bump version to 2020.01

coap-chat/coap.c, spectrum-scanner/main.c, spectrum-scanner/tools/plot_rssi.py
All apps need to be checked if they work according to their README.
=> RIOT: update to 2020.07

coap-chat/coap.c, coap-chat/main.c
This adapts the coap-chat application to use the new gcoap API, as `gcoap_finish` has been deprecated and removed. Also, removes the inclusion of `kernel_types.h` which has been removed as well.
Run the application following the README, it should compile and work as usual.
=> coap-chat: adapt to new gcoap API

.travis.yml
The PR removes flake8 as travis is still running Python 3.5.
https://travis-ci.org/github/RIOT-OS/applications
@miri64
=> travis: Remove flake8

sniffer/tools/sniffer.py
https://github.com/RIOT-OS/applications/pull/61#issuecomment-1251113899
=> sniffer: correct handling of byte strings
